import { describe, expect, it } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  biomeAffinity,
  biomeAt,
  BIOME_DIRT,
  BIOME_FOREST,
  BIOME_GRASS,
  BIOME_KNOBS_DEFAULT,
  BIOME_MARSH,
  BIOME_ROCK,
  BIOME_SAND,
  BIOME_SHORE,
  BIOME_SNOW,
  BIOME_WATER,
  isPassableBiome,
  type BiomeKnobs,
  type BiomeType,
} from '../../src/index';

// Committed wire vectors — generated by the chain side
// (programs/novus_mundus/tests/biome_wire_vector{,_knobs}.rs) and
// asserted on every CI run. SDK side asserts identical output here.
// Drift on either side fails the build.

interface BiomeVectorEntry {
  seed: number;
  ox: number;
  oy: number;
  biome: number;
}

interface BiomeKnobsVectorEntry extends BiomeVectorEntry {
  preset: string;
  water_level_delta: number;
  temp_bias: number;
  moisture_bias: number;
  coast: number;
  landmass_seed: number;
}

function loadWireVector(): BiomeVectorEntry[] {
  const path = join(__dirname, '..', 'fixtures', 'biome-vectors.json');
  const text = readFileSync(path, 'utf8');
  return JSON.parse(text) as BiomeVectorEntry[];
}

function loadKnobsWireVector(): BiomeKnobsVectorEntry[] {
  const path = join(__dirname, '..', 'fixtures', 'biome-vectors-knobs.json');
  const text = readFileSync(path, 'utf8');
  return JSON.parse(text) as BiomeKnobsVectorEntry[];
}

describe('biome wire vector', () => {
  it('SDK biomeAt matches the committed chain output for every tuple (default knobs)', () => {
    const vector = loadWireVector();
    expect(vector.length).toBeGreaterThan(0);
    for (const entry of vector) {
      const got = biomeAt(entry.seed, entry.ox, entry.oy, BIOME_KNOBS_DEFAULT);
      expect(got).toBe(entry.biome);
    }
  });

  it('SDK biomeAt matches the committed chain output for every knob preset', () => {
    const vector = loadKnobsWireVector();
    expect(vector.length).toBeGreaterThan(0);
    for (const entry of vector) {
      const knobs: BiomeKnobs = {
        waterLevelDelta: entry.water_level_delta,
        tempBias: entry.temp_bias,
        moistureBias: entry.moisture_bias,
        coast: entry.coast,
        landmassSeed: entry.landmass_seed,
      };
      const got = biomeAt(entry.seed, entry.ox, entry.oy, knobs);
      if (got !== entry.biome) {
        // Surface the preset label on drift — much faster than
        // bisecting a 1000-entry diff.
        throw new Error(
          `drift in preset "${entry.preset}" at seed=${entry.seed} ox=${entry.ox} oy=${entry.oy}: chain=${entry.biome} sdk=${got}`,
        );
      }
    }
  });
});

describe('biome semantics', () => {
  it('biomeAt is deterministic', () => {
    for (const seed of [0, 1, 0xcafe0000, 0xdeadbeef]) {
      for (const oy of [-1000, -100, 0, 100, 1000]) {
        for (const ox of [-1000, -100, 0, 100, 1000]) {
          const a = biomeAt(seed, ox, oy);
          const b = biomeAt(seed, ox, oy);
          expect(a).toBe(b);
        }
      }
    }
  });

  it('isPassableBiome rejects only water', () => {
    const all: BiomeType[] = [
      BIOME_GRASS,
      BIOME_SAND,
      BIOME_SNOW,
      BIOME_DIRT,
      BIOME_WATER,
      BIOME_ROCK,
      BIOME_FOREST,
      BIOME_MARSH,
      BIOME_SHORE,
    ];
    for (const b of all) {
      const passable = isPassableBiome(b);
      if (b === BIOME_WATER) {
        expect(passable).toBe(false);
      } else {
        expect(passable).toBe(true);
      }
    }
  });

  it('shore cells have a water neighbour', () => {
    // Same invariant the chain tests check, mirrored client-side so
    // the rendered shoreline never lies about passability.
    for (const seed of [0xcafe0000, 0xdeadbeef]) {
      for (let oy = -100; oy < 100; oy++) {
        for (let ox = -100; ox < 100; ox++) {
          if (biomeAt(seed, ox, oy) !== BIOME_SHORE) continue;
          const neighbours = [
            biomeAt(seed, ox - 1, oy),
            biomeAt(seed, ox + 1, oy),
            biomeAt(seed, ox, oy - 1),
            biomeAt(seed, ox, oy + 1),
          ];
          expect(neighbours).toContain(BIOME_WATER);
        }
      }
    }
  });

  it('biomeAffinity table direction matches the chain', () => {
    expect(biomeAffinity(BIOME_GRASS)).toEqual({
      miningBps: 0,
      fishingBps: 0,
      combatBps: 0,
    });
    expect(biomeAffinity(BIOME_WATER)).toEqual({
      miningBps: 0,
      fishingBps: 0,
      combatBps: 0,
    });
    expect(biomeAffinity(BIOME_ROCK).miningBps).toBeGreaterThan(0);
    expect(biomeAffinity(BIOME_SNOW).miningBps).toBeGreaterThan(0);
    expect(biomeAffinity(BIOME_SHORE).fishingBps).toBeGreaterThan(0);
    expect(biomeAffinity(BIOME_MARSH).fishingBps).toBeGreaterThan(0);
    expect(biomeAffinity(BIOME_FOREST).combatBps).toBeLessThan(0);
    expect(biomeAffinity(BIOME_SAND).combatBps).toBeGreaterThan(0);
    expect(biomeAffinity(BIOME_ROCK).combatBps).toBeGreaterThan(0);
  });
});

