// Codegen: derive template-map.generated.ts from the SDK's hero roster.
//
// The roster (sdks/novus-mundus-ts/cli/data/heroes.ts) is the single source of
// truth for tier/category/buffs/meditation-city. Re-emitting from it here keeps
// the portrait route from silently drifting when the roster changes.
//
// Run: bun run apps/web/scripts/gen-template-map.ts
// Hooked from apps/web/package.json prebuild so `bun run build` regenerates.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  HERO_TEMPLATES,
  RESERVE_HEROES,
} from "../../../sdks/novus-mundus-ts/cli/data/heroes";
import { tierFromMintCost } from "novus-mundus-sdk";

const all = [...HERO_TEMPLATES, ...RESERVE_HEROES];

const seen = new Set<number>();
const rows: string[] = [];
for (const h of all) {
  if (seen.has(h.templateId)) {
    throw new Error(
      `gen-template-map: duplicate templateId ${h.templateId} (${h.name})`,
    );
  }
  seen.add(h.templateId);
  const tier = tierFromMintCost(h.mintCostLamports);
  const buffs = h.buffs.map((b) => b.stat).join(", ");
  const name = JSON.stringify(h.name);
  rows.push(
    `  ${h.templateId}: { name: ${name}, tier: ${tier}, category: ${h.category}, buffs: [${buffs}], meditationCity: ${h.meditationCityId} },`,
  );
}

const out = `// AUTO-GENERATED by apps/web/scripts/gen-template-map.ts. Do not edit.
// Source: sdks/novus-mundus-ts/cli/data/heroes.ts (HERO_TEMPLATES + RESERVE_HEROES).
// Tier is derived via tierFromMintCost (mirrors chain state/hero.rs).

import type { HeroTier } from "./palette";

export interface TemplateMeta {
  /** Display name from heroes.ts; matches the on-chain HeroTemplate.name and the minted MPL Core Asset name (≤ 32 bytes). */
  name: string;
  tier: HeroTier;
  category: 0 | 1 | 2 | 3 | 4;
  /** BuffStat enum ids (1..18), up to 4. Drives Layer 7 icon overlay. */
  buffs: number[];
  /** meditation_city_id from heroes.ts. 0 = "everywhere" sentinel. */
  meditationCity: number;
}

export const TEMPLATE_META: Readonly<Record<number, TemplateMeta>> = {
${rows.join("\n")}
};

export function getTemplateMeta(templateId: number): TemplateMeta | null {
  return TEMPLATE_META[templateId] ?? null;
}
`;

const target = join(
  __dirname,
  "../src/lib/hero-image/template-map.generated.ts",
);
writeFileSync(target, out);
console.log(`wrote ${target} (${all.length} templates)`);
